--- #YAML:1.0
name:               Business-OnlinePayment-AuthorizeNet
version:            3.21
abstract:           ~
author:
    - Ivan Kohler <ivan-authorizenet@420.am>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Business::OnlinePayment:  3
    Business::OnlinePayment::HTTPS:  0
    Net::SSLeay:          0
    Test::More:           0.42
    Text::CSV_XS:         0
    Tie::IxHash:          0
    XML::Simple:          0
    XML::Writer:          0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
